### ISSUE TITLE
CAPD Should use the real cloud-init to execute bootstrap scripts

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api#3488]
**Detailed Description**

As of today CAPD uses a custom [cloud-init interpreter](https://github.com/kubernetes-sigs/cluster-api/tree/6b830c4f8e6d72da8202b2a8b79e88039fb4e39c/test/infrastructure/docker/cloudinit) to run the bootstrap script, but the side effect of this is that the machine creation process is slightly different from other providers where the bootstrap process happens during the machine startup (while in CAPD is an explicit step in the controller). 

[Here](https://github.com/dippynark/cluster-api-provider-kubernetes/blob/672ac0c1509ff8e504440b168bce77c6b18b5246/controllers/kubernetesmachine_controller.go) there is a possible alternative solution, that injects a script to install and run "the real" cloud-init on a kind node

/kind feature

**Comment by fabriziopandini** [comment]
I have done some digging around this topic, and the only possible solution that could potentially work is to create custom images for CAPD instead of using Kind ones.
I'm not sure we want to go down this road, it requires forking/duplicating a lot of code...

**Comment by vincepri** [comment]
Probably worth keeping the issue around if someone wants to tackle it, although we're probably not going to prioritize this anytime soon.

/priority backlog

**Comment by randomvariable** [comment]
Yup. Came to the same conclusion when I last looked at this.

There's also a bunch of issues with running cloud-init in a container:
* Need to disable all the datasources by writing:
```yaml
datasource_list: [ iid-datasource-none ]
```
to /etc/cloud/cloud.cfg.d/91-datasource.cfg

Can then run `cloud-init -f /<mounted datasource file> init`.

However, cloud-init still does things where it's expecting root access to the Linux kernel, e.g.:
```
FileNotFoundError: [Errno 2] No such file or directory: b'udevadm': b'udevadm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 653, in status_wrapper
    ret = functor(name, args)
  File "/usr/lib/python3/dist-packages/cloudinit/cmd/main.py", line 341, in main_init
    init.apply_network_config(bring_up=not args.local)
  File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 708, in apply_network_config
    return self.distro.apply_network_config(netcfg, bring_up=bring_up)
  File "/usr/lib/python3/dist-packages/cloudinit/distros/__init__.py", line 180, in apply_network_config
    dev_names = self._write_network_config(netconfig)
  File "/usr/lib/python3/dist-packages/cloudinit/distros/debian.py", line 115, in _write_network_config
    return self._supported_write_network_config(netconfig)
  File "/usr/lib/python3/dist-packages/cloudinit/distros/__init__.py", line 95, in _supported_write_network_config
    renderer.render_network_config(network_config)
  File "/usr/lib/python3/dist-packages/cloudinit/net/renderer.py", line 56, in render_network_config
    templates=templates, target=target)
  File "/usr/lib/python3/dist-packages/cloudinit/net/netplan.py", line 236, in render_network_state
    self._net_setup_link(run=self._postcmds)
  File "/usr/lib/python3/dist-packages/cloudinit/net/netplan.py", line 256, in _net_setup_link
    util.subp(cmd, capture=True)
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2137, in subp
    stderr="-" if decode else b"-")
cloudinit.util.ProcessExecutionError: Unexpected error while running command.
Command: ['udevadm', 'test-builtin', 'net_setup_link', '/sys/class/net/eth0']
Exit code: -
Reason: [Errno 2] No such file or directory: b'udevadm': b'udevadm'
Stdout: -
```

Paring down the modules to this doesn't solve it:
```
# The modules that run in the 'init' stage
cloud_init_modules:
 - write-files
 - ca-certs

# The modules that run in the 'config' stage
cloud_config_modules:
# Emit the cloud config ready event
# this can be used by upstart jobs for 'start on cloud-config'.
 - runcmd
cloud_final_modules:
 - scripts-vendor
 - scripts-per-once
 - scripts-per-boot
 - scripts-per-instance
 - scripts-user
 - keys-to-console
 - final-message
 - power-state-change
```
