### ISSUE TITLE
Controllers test suite is very flaky

### ISSUE THREAD

**Issue by invidian** [kubernetes-sigs/cluster-api#4342]
**What steps did you take and what happened:**
1. Run `while make test TEST_ARGS='-count 1' ; do sleep 1; done`
2. Tests fails with various errors.

**What did you expect to happen:**
Tests are passing.

**Anything else you would like to add:**

Sometimes, test fails with concurrent map writes. Running `make test TEST_ARGS=-race` throws a lot of warnings with `WARNING: DATA RACE`. I think some (or maybe majority) might be actually happening outside CAPI, but still, the test suite remains unstable. I was not able to identify the exact place when the concurrent map write occurs, as it prints thousands call stacks from goroutines. First one is:
```
fatal error: concurrent map read and map write

goroutine 1739 [running]:
runtime.throw(0x1cb49bf, 0x21)
        /usr/lib/go/src/runtime/panic.go:1117 +0x72 fp=0xc0007b3588 sp=0xc0007b3558 pc=0x43a592
runtime.mapaccess2(0x1a447c0, 0xc0002c8450, 0xc0007b3640, 0xc000366ae8, 0x1b21401)
        /usr/lib/go/src/runtime/map.go:469 +0x255 fp=0xc0007b35c8 sp=0xc0007b3588 pc=0x411875
k8s.io/apimachinery/pkg/runtime.(*Scheme).ObjectKinds(0xc00025efc0, 0x1eccef8, 0xc00025ee70, 0xc00086e3c0, 0xc0007b3738, 0x2b8b430, 0xc0001da270, 0x2b8b430, 0xc000e58558)
        /home/invidian/.cache/go/pkg/mod/k8s.io/apimachinery@v0.21.0-beta.1/pkg/runtime/scheme.go:263 +0x256 fp=0xc0007b3690 sp=0xc0007b35c8 pc=0x93cc96
sigs.k8s.io/controller-runtime/pkg/client/apiutil.GVKForObject(0x1eccef8, 0xc00025ee70, 0xc00025efc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0007760c0, ...)
        /home/invidian/.cache/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2-0.20210314174504-df2c43d8896d/pkg/client/apiutil/apimachinery.go:97 +0x21d fp=0xc0007b3728 sp=0xc0007b3690 pc=0x133d49d
sigs.k8s.io/controller-runtime/pkg/client.(*delegatingReader).shouldBypassCache(0xc0005f42c0, 0x1eccef8, 0xc00025ee70, 0x1eccef8, 0xc00025ee70, 0x203000)
        /home/invidian/.cache/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2-0.20210314174504-df2c43d8896d/pkg/client/split.go:103 +0x79 fp=0xc0007b3800 sp=0xc0007b3728 pc=0x1350979
sigs.k8s.io/controller-runtime/pkg/client.(*delegatingReader).List(0xc0005f42c0, 0x1ef70c8, 0xc0000421d8, 0x1f0db70, 0xc00025ee70, 0xc0007760e0, 0x2, 0x2, 0x8, 0x10)
        /home/invidian/.cache/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2-0.20210314174504-df2c43d8896d/pkg/client/split.go:135 +0x6a fp=0xc0007b3860 sp=0xc0007b3800 pc=0x1350e4a
sigs.k8s.io/controller-runtime/pkg/client.(*delegatingClient).List(0xc00107aaf0, 0x1ef70c8, 0xc0000421d8, 0x1f0db70, 0xc00025ee70, 0xc0007760e0, 0x2, 0x2, 0x1bc3601, 0xc000828a70)
        <autogenerated>:1 +0x96 fp=0xc0007b38c0 sp=0xc0007b3860 pc=0x1357616
sigs.k8s.io/cluster-api/test/helpers.(*TestEnvironment).List(0xc000f5d710, 0x1ef70c8, 0xc0000421d8, 0x1f0db70, 0xc00025ee70, 0xc0007760e0, 0x2, 0x2, 0x0, 0x0)
        <autogenerated>:1 +0x97 fp=0xc0007b3920 sp=0xc0007b38c0 pc=0x17fff97
sigs.k8s.io/cluster-api/controllers.(*MachineHealthCheckReconciler).machineToMachineHealthCheck(0xc0009de4b0, 0x1f204c0, 0xc0012be000, 0x0, 0x0, 0x0)
        /home/invidian/data/workspaces/clusterapi-flatcar/cluster-api/controllers/machinehealthcheck_controller.go:461 +0x1fe fp=0xc0007b3a08 sp=0xc0007b3920 pc=0x18254be
sigs.k8s.io/cluster-api/controllers.(*MachineHealthCheckReconciler).machineToMachineHealthCheck-fm(0x1f204c0, 0xc0012be000, 0x0, 0x0, 0x0)
        /home/invidian/data/workspaces/clusterapi-flatcar/cluster-api/controllers/machinehealthcheck_controller.go:454 +0x47 fp=0xc0007b3a48 sp=0xc0007b3a08 pc=0x18a85c7
sigs.k8s.io/controller-runtime/pkg/handler.(*enqueueRequestsFromMapFunc).mapAndEnqueue(0xc0009c4538, 0x1f0daa0, 0xc000a89080, 0x1f204c0, 0xc0012be000, 0xc0007b3b10)
        /home/invidian/.cache/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2-0.20210314174504-df2c43d8896d/pkg/handler/enqueue_mapped.go:80 +0x58 fp=0xc0007b3ae0 sp=0xc0007b3a48 pc=0x1383c78
sigs.k8s.io/controller-runtime/pkg/handler.(*enqueueRequestsFromMapFunc).Update(0xc0009c4538, 0x1f204c0, 0xc0017d4240, 0x1f204c0, 0xc0012be000, 0x1f0daa0, 0xc000a89080)
        /home/invidian/.cache/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2-0.20210314174504-df2c43d8896d/pkg/handler/enqueue_mapped.go:64 +0x12a fp=0xc0007b3c60 sp=0xc0007b3ae0 pc=0x13839ea
sigs.k8s.io/controller-runtime/pkg/source/internal.EventHandler.OnUpdate(0x1ef78a8, 0xc0009c4538, 0x1f0daa0, 0xc000a89080, 0xc000af8270, 0x1, 0x1, 0x1c5eba0, 0xc0017d4240, 0x1c5eba0, ...)
        /home/invidian/.cache/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2-0.20210314174504-df2c43d8896d/pkg/source/internal/eventsource.go:94 +0x1b0 fp=0xc0007b3d08 sp=0xc0007b3c60 pc=0x13b95f0
sigs.k8s.io/controller-runtime/pkg/source/internal.(*EventHandler).OnUpdate(0xc000876e00, 0x1c5eba0, 0xc0017d4240, 0x1c5eba0, 0xc0012be000)
        <autogenerated>:1 +0xd6 fp=0xc0007b3da8 sp=0xc0007b3d08 pc=0x13ba236
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /home/invidian/.cache/go/pkg/mod/k8s.io/client-go@v0.21.0-beta.1/tools/cache/shared_informer.go:775 +0x1c5 fp=0xc0007b3e28 sp=0xc0007b3da8 pc=0x1371c25
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000178760)
        /home/invidian/.cache/go/pkg/mod/k8s.io/apimachinery@v0.21.0-beta.1/pkg/util/wait/wait.go:155 +0x5f fp=0xc0007b3e78 sp=0xc0007b3e28 pc=0xa1053f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0007b3f60, 0x1ec2320, 0xc000b3eb40, 0x1a20f01, 0xc000797380)
        /home/invidian/.cache/go/pkg/mod/k8s.io/apimachinery@v0.21.0-beta.1/pkg/util/wait/wait.go:156 +0x9b fp=0xc0007b3f00 sp=0xc0007b3e78 pc=0xa0f27b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000178760, 0x3b9aca00, 0x0, 0xc000479301, 0xc000797380)
        /home/invidian/.cache/go/pkg/mod/k8s.io/apimachinery@v0.21.0-beta.1/pkg/util/wait/wait.go:133 +0x98 fp=0xc0007b3f38 sp=0xc0007b3f00 pc=0xa0f1b8
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /home/invidian/.cache/go/pkg/mod/k8s.io/apimachinery@v0.21.0-beta.1/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc00037c380)
        /home/invidian/.cache/go/pkg/mod/k8s.io/client-go@v0.21.0-beta.1/tools/cache/shared_informer.go:771 +0x95 fp=0xc0007b3f88 sp=0xc0007b3f38 pc=0x136c0f5
k8s.io/client-go/tools/cache.(*processorListener).run-fm()
        /home/invidian/.cache/go/pkg/mod/k8s.io/client-go@v0.21.0-beta.1/tools/cache/shared_informer.go:765 +0x33 fp=0xc0007b3fa0 sp=0xc0007b3f88 pc=0x1372133
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0003f4bc0, 0xc0009d65f0)
        /home/invidian/.cache/go/pkg/mod/k8s.io/apimachinery@v0.21.0-beta.1/pkg/util/wait/wait.go:73 +0x51 fp=0xc0007b3fd0 sp=0xc0007b3fa0 pc=0xa10491
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0007b3fd8 sp=0xc0007b3fd0 pc=0x474921
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /home/invidian/.cache/go/pkg/mod/k8s.io/apimachinery@v0.21.0-beta.1/pkg/util/wait/wait.go:71 +0x65
```

It seems to be happening in mostly in`controllers` package.

I also got the following sometimes:
```
panic: send on closed channel

goroutine 1433 [running]:
k8s.io/apimachinery/pkg/watch.(*Broadcaster).ActionOrDrop(0xc000b3cfc0, 0x1c8c796, 0x5, 0x1eca4a0, 0xc0003c5b80, 0x1c99573)
        /home/invidian/.cache/go/pkg/mod/k8s.io/apimachinery@v0.21.0-beta.1/pkg/watch/mux.go:222 +0x7f
k8s.io/client-go/tools/record.(*recorderImpl).generateEvent(0xc000c96a00, 0x1eccf48, 0xc001ed5340, 0x0, 0x1c8f867, 0x7, 0x1c99573, 0xe, 0xc001b05c70, 0x6a)
        /home/invidian/.cache/go/pkg/mod/k8s.io/client-go@v0.21.0-beta.1/tools/record/event.go:346 +0x3d7
k8s.io/client-go/tools/record.(*recorderImpl).Event(...)
        /home/invidian/.cache/go/pkg/mod/k8s.io/client-go@v0.21.0-beta.1/tools/record/event.go:352
k8s.io/client-go/tools/record.(*recorderImpl).Eventf(0xc000c96a00, 0x1eccf48, 0xc001ed5340, 0x1c8f867, 0x7, 0x1c99573, 0xe, 0x1c8ad5b, 0x2, 0xc0017854c0, ...)
        /home/invidian/.cache/go/pkg/mod/k8s.io/client-go@v0.21.0-beta.1/tools/record/event.go:356 +0xd6
sigs.k8s.io/controller-runtime/pkg/internal/recorder.(*lazyRecorder).Eventf(0xc000c97e80, 0x1eccf48, 0xc001ed5340, 0x1c8f867, 0x7, 0x1c99573, 0xe, 0x1c8ad5b, 0x2, 0xc0017854c0, ...)
        /home/invidian/.cache/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2-0.20210314174504-df2c43d8896d/pkg/internal/recorder/recorder.go:151 +0xd2
sigs.k8s.io/cluster-api/controllers.(*MachineSetReconciler).Reconcile(0xc000c97bc0, 0x1ef7138, 0xc0016da780, 0xc000b88ad0, 0x7, 0xc00143aa20, 0x13, 0xc0016da700, 0x0, 0x0, ...)
        /home/invidian/data/workspaces/clusterapi-flatcar/cluster-api/controllers/machineset_controller.go:160 +0x658
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002739a0, 0x1ef7090, 0xc000c4a640, 0x1ad4ec0, 0xc000c12840)
        /home/invidian/.cache/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2-0.20210314174504-df2c43d8896d/pkg/internal/controller/controller.go:298 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0002739a0, 0x1ef7090, 0xc000c4a640, 0xc000b5c000)
        /home/invidian/.cache/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2-0.20210314174504-df2c43d8896d/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc000b46010, 0xc0002739a0, 0x1ef7090, 0xc000c4a640)
        /home/invidian/.cache/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2-0.20210314174504-df2c43d8896d/pkg/internal/controller/controller.go:214 +0x6b
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /home/invidian/.cache/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.2-0.20210314174504-df2c43d8896d/pkg/internal/controller/controller.go:210 +0x425
FAIL    sigs.k8s.io/cluster-api/controllers     26.846s
FAIL
make: *** [Makefile:119: test] Error 1
```

Or:
```
--- FAIL: TestMachineHealthCheck_Reconcile (148.38s)
    --- FAIL: TestMachineHealthCheck_Reconcile/it_doesn't_mark_anything_unhealthy_when_all_Machines_are_healthy (83.97s)
        machinehealthcheck_controller_test.go:2274:
            Expected success, but got an error:
                <errors.aggregate | len:1, cap:1>: [
                    {
                        ErrStatus: {
                            TypeMeta: {Kind: "", APIVersion: ""},
                            ListMeta: {
                                SelfLink: "",
                                ResourceVersion: "",
                                Continue: "",
                                RemainingItemCount: nil,
                            },
                            Status: "Failure",
                            Message: "Timeout: request did not complete within requested timeout 34s",
                            Reason: "Timeout",
                            Details: {Name: "", Group: "", Kind: "", UID: "", Causes: nil, RetryAfterSeconds: 0},
                            Code: 504,
                        },
                    },
                ]
                Timeout: request did not complete within requested timeout 34s
    --- FAIL: TestMachineHealthCheck_Reconcile/it_marks_unhealthy_machines_for_remediation_when_there_is_one_unhealthy_Machine (39.59s)
        machinehealthcheck_controller_test.go:2500:
            Expected success, but got an error:
                <errors.aggregate | len:1, cap:1>: [
                    {
                        ErrStatus: {
                            TypeMeta: {Kind: "", APIVersion: ""},
                            ListMeta: {
                                SelfLink: "",
                                ResourceVersion: "",
                                Continue: "",
                                RemainingItemCount: nil,
                            },
                            Status: "Failure",
                            Message: "Timeout: request did not complete within requested timeout 34s",
                            Reason: "Timeout",
                            Details: {Name: "", Group: "", Kind: "", UID: "", Causes: nil, RetryAfterSeconds: 0},
                            Code: 504,
                        },
                    },
                ]
                Timeout: request did not complete within requested timeout 34s
```

Or

```
--- FAIL: TestWatches (56.83s)
    machine_controller_test.go:162:
        Timed out after 30.000s.
        Expected
            <bool>: false
        to be true
```

**Environment:**

- Cluster-api version: 69aa31e39

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by vincepri** [comment]
@invidian Thanks for the report. The race condition is a bug we've identified in Controller Runtime and its usage of the client-go libraries, it needs to be investigated a bit more but we've made some progress there in the right direction.

Regarding timeouts and such, it could be a number of things. Up until recently I've noticed (in #4308) that we were not waiting for webhooks to be fully up before running other tests, which could cause requests to timeout.

The other part of it is resource starvation, which we can't do much about it. The test suite, especially when running in parallel, spins up multiple api-server and etcd instances which might cause CPU contention between resources.

/milestone Next
/priority important-longterm

**Comment by invidian** [comment]
>The other part of it is resource starvation, which we can't do much about it. The test suite, especially when running in parallel, spins up multiple api-server and etcd instances which might cause CPU contention between resources.

I'm doing some tests now on a beefy dedicated machine to make sure those are not caused by the CPU starvation. I was able to reproduce all of them except `TestMachineHealthCheck_Reconcile/it_doesn't_mark_anything_unhealthy_when_all_Machines_are_healthy`, so this one was perhaps caused by CPU limits.

I also hit the following twice:
```
Creating new test environment
panic: customresourcedefinitions.apiextensions.k8s.io "clusterresourcesetbindings.addons.cluster.x-k8s.io" already exists

goroutine 1 [running]:
sigs.k8s.io/cluster-api/test/helpers.NewTestEnvironment(0x1ec0360)
        /root/cluster-api/test/helpers/envtest.go:128 +0x118a
sigs.k8s.io/cluster-api/controllers.TestMain(0xc000242080)
        /root/cluster-api/controllers/suite_test.go:52 +0x98
main.main()
        _testmain.go:143 +0x165
```

**Comment by vincepri** [comment]
@invidian Have you tried to reproduce on the latest commit?

**Comment by invidian** [comment]
I'll give it a try when I find some time :+1:

**Comment by invidian** [comment]
First run on commit 686aef6a95613cfe87631e92a11cb55349da4725 yielded the following:
```console
2021/06/25 06:47:13 http: TLS handshake error from 127.0.0.1:56138: EOF
E0625 06:47:14.883050 3474289 deleg.go:144]  "msg"="Error health checking cluster" "error"="Cluster.cluster.x-k8s.io \"my-cluster\" not found"  "cluster"="workload-cluster2-rg4vl/my-cluster"
--- FAIL: TestGetWorkloadCluster (2.23s)
    --- FAIL: TestGetWorkloadCluster/returns_a_workload_cluster (0.15s)
        cluster_test.go:205:
            Unexpected error:
                <*errors.withStack | 0xc0005085e8>: {
                    error: <*errors.withMessage | 0xc000dc0000>{
                        cause: <*errors.StatusError | 0xc000538000>{
                            ErrStatus: {
                                TypeMeta: {Kind: "", APIVersion: ""},
                                ListMeta: {
                                    SelfLink: "",
                                    ResourceVersion: "",
                                    Continue: "",
                                    RemainingItemCount: nil,
                                },
                                Status: "Failure",
                                Message: "Secret \"my-cluster-kubeconfig\" not found",
                                Reason: "NotFound",
                                Details: {
                                    Name: "my-cluster-kubeconfig",
                                    Group: "",
                                    Kind: "Secret",
                                    UID: "",
                                    Causes: nil,
                                    RetryAfterSeconds: 0,
                                },
                                Code: 404,
                            },
                        },
                        msg: "failed to retrieve kubeconfig secret for Cluster workload-cluster2-rg4vl/my-cluster",
                    },
                    stack: [0x15f4e1e, 0x189f192, 0x18d0ff5, 0x52516f, 0x474341],
                }
                failed to retrieve kubeconfig secret for Cluster workload-cluster2-rg4vl/my-cluster: Secret "my-cluster-kubeconfig" not found
            occurred
FAIL
I0625 06:47:21.391278 3474289 deleg.go:130] controller-runtime/webhook "msg"="shutting down webhook server"
FAIL    sigs.k8s.io/cluster-api/controlplane/kubeadm/internal   29.446s
```

There was also:
```
Creating new test environment
panic: unable to grab random port for serving webhooks on: lstat /home/invidian/.cache/kubebuilder-envtest/./port-39815: no such file or directory

goroutine 1 [running]:
sigs.k8s.io/cluster-api/internal/envtest.New(0x0, 0x0, 0x0, 0x1)
        /home/invidian/data/workspaces/clusterapi-flatcar/cluster-api/internal/envtest/environment.go:134 +0x1ddb
sigs.k8s.io/cluster-api/bootstrap/kubeadm/controllers.TestMain(0xc000134000)
        /home/invidian/data/workspaces/clusterapi-flatcar/cluster-api/bootstrap/kubeadm/controllers/suite_test.go:36 +0x8e
main.main()
        _testmain.go:97 +0x165
FAIL    sigs.k8s.io/cluster-api/bootstrap/kubeadm/controllers   16.655s
```

And:

```
Creating new test environment
E0625 07:13:34.023153 3550268 deleg.go:144] controller-runtime/test-env "msg"="unable to start the controlplane" "error"="timeout waiting for process kube-apiserver to start"  "tries"=0
E0625 07:13:34.123651 3550268 deleg.go:144] controller-runtime/test-env "msg"="unable to start the controlplane" "error"="timeout waiting for process kube-apiserver to start successfully (it may have failed to start, or stopped unexpectedly before becoming ready)"  "tries"=1
E0625 07:13:34.224198 3550268 deleg.go:144] controller-runtime/test-env "msg"="unable to start the controlplane" "error"="timeout waiting for process kube-apiserver to start successfully (it may have failed to start, or stopped unexpectedly before becoming ready)"  "tries"=2
E0625 07:13:34.391194 3550268 deleg.go:144] controller-runtime/test-env "msg"="unable to start the controlplane" "error"="timeout waiting for process kube-apiserver to start successfully (it may have failed to start, or stopped unexpectedly before becoming ready)"  "tries"=3
E0625 07:14:34.440943 3550268 deleg.go:144] controller-runtime/test-env "msg"="unable to start the controlplane" "error"="timeout waiting for process kube-apiserver to start"  "tries"=4
panic: unable to start control plane itself: failed to start the controlplane. retried 5 times: timeout waiting for process kube-apiserver to start

goroutine 1 [running]:
sigs.k8s.io/cluster-api/internal/envtest.New(0x0, 0x0, 0x0, 0x1)
        /home/invidian/data/workspaces/clusterapi-flatcar/cluster-api/internal/envtest/environment.go:134 +0x1ddb
sigs.k8s.io/cluster-api/util/patch.TestMain(0xc0001bc100)
        /home/invidian/data/workspaces/clusterapi-flatcar/cluster-api/util/patch/suite_test.go:41 +0x8e
main.main()
        _testmain.go:51 +0x165
FAIL    sigs.k8s.io/cluster-api/util/patch      124.918s
```

And this one after 30 minutes of running continuously: 
```
I0625 07:52:57.099856 3650354 deleg.go:130] controller-runtime/certwatcher "msg"="Starting certificate watcher"
I0625 07:52:57.099893 3650354 deleg.go:130] controller-runtime/webhook "msg"="serving webhook server"  "host"="" "port"=46217
2021/06/25 07:52:58 http: TLS handshake error from 127.0.0.1:54536: EOF
E0625 07:52:58.740706 3650354 cluster_cache.go:379]  "msg"="Error health checking cluster" "error"="Get \"https://127.0.0.1:40553/?timeout=50ms\": context deadline exceeded"  "cluster"="cluster-cache-test-ppvgw/test-cluster"
E0625 07:53:01.221001 3650354 cluster_cache.go:379]  "msg"="Error health checking cluster" "error"="the server could not find the requested resource"  "cluster"="cluster-cache-test-ztvwq/test-cluster"
E0625 07:53:01.773282 3650354 cluster_cache.go:379]  "msg"="Error health checking cluster" "error"="Get \"http://127.0.0.1:43111/?timeout=50ms\": dial tcp 127.0.0.1:43111: connect: connection refused"  "cluster"="cluster-cache-test-5flc4/test-cluster"
--- FAIL: TestClusterCacheHealthCheck (4.18s)
    --- FAIL: TestClusterCacheHealthCheck/when_health_checking_clusters (4.18s)
        --- FAIL: TestClusterCacheHealthCheck/when_health_checking_clusters/with_a_healthy_cluster (2.75s)
            cluster_cache_healthcheck_test.go:56: Setting up a new manager
            cluster_cache_healthcheck_test.go:65: Starting the manager
            cluster_cache_healthcheck_test.go:73: Setting up a ClusterCacheTracker
            cluster_cache_healthcheck_test.go:77: Creating a namespace for the test
            cluster_cache_healthcheck_test.go:81: Creating a test cluster
            cluster_cache_healthcheck_test.go:93: Creating a test cluster kubeconfig
            cluster_cache_healthcheck_test.go:132:
                Failed after 0.503s.
                Expected
                    <bool>: false
                to be true
            cluster_cache_healthcheck_test.go:104: Deleting any Secrets
            cluster_cache_healthcheck_test.go:106: Deleting any Clusters
            cluster_cache_healthcheck_test.go:108: Stopping the manager
I0625 07:53:02.338780 3650354 controller.go:165] controller-runtime/manager/controller/cluster "msg"="Starting EventSource" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Cluster" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{"controlPlaneEndpoint":{"host":"","port":0}},"status":{"infrastructureReady":false}}}
I0625 07:53:02.338824 3650354 controller.go:173] controller-runtime/manager/controller/cluster "msg"="Starting Controller" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Cluster"
I0625 07:53:02.440765 3650354 controller.go:207] controller-runtime/manager/controller/cluster "msg"="Starting workers" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Cluster" "worker count"=1
I0625 07:53:02.724466 3650354 controller.go:227] controller-runtime/manager/controller/cluster "msg"="Shutdown signal received, waiting for all workers to finish" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Cluster"
I0625 07:53:02.724629 3650354 controller.go:229] controller-runtime/manager/controller/cluster "msg"="All workers finished" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Cluster"
I0625 07:53:02.760537 3650354 controller.go:165] controller-runtime/manager/controller/machinedeployment "msg"="Starting EventSource" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="MachineDeployment" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{"clusterName":"","selector":{},"template":{"metadata":{},"spec":{"clusterName":"","bootstrap":{},"infrastructureRef":{}}}},"status":{}}}
I0625 07:53:02.760584 3650354 controller.go:173] controller-runtime/manager/controller/machinedeployment "msg"="Starting Controller" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="MachineDeployment"
I0625 07:53:02.865708 3650354 controller.go:207] controller-runtime/manager/controller/machinedeployment "msg"="Starting workers" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="MachineDeployment" "worker count"=1
I0625 07:53:02.942662 3650354 controller.go:130] controller-runtime/manager/controller/machinedeployment "msg"="Starting EventSource" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="MachineDeployment" "source"={}
I0625 07:53:03.491224 3650354 controller.go:227] controller-runtime/manager/controller/machinedeployment "msg"="Shutdown signal received, waiting for all workers to finish" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="MachineDeployment"
FAIL
Stopping the test environment
I0625 07:53:03.554021 3650354 deleg.go:130] controller-runtime/webhook "msg"="shutting down webhook server"
FAIL    sigs.k8s.io/cluster-api/controllers/remote      34.539s
```

Given that rate of errors is not very high, I was running them on the laptop, and that errors are not strictly related to CAPI tests, I _think_ this can be closed now. Time will verify when I get some time to contribute to CAPI again :smile:

Whatever you did to make tests more stable, thanks!

**Comment by fabriziopandini** [comment]
/close
As per comment above
Thanks for taking time to check this!
