### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference - Reconciling Bastion

### ISSUE THREAD

**Issue by danrca** [kubernetes-sigs/cluster-api#6484]
**What steps did you take and what happened:**
Was working through the quickstart guide. Dropped it down to 1 machine since I was having issues with working machines coming up. It was complaining about certs, so I added "verify=false" to ignore that for the time being.  This is on openstack without a loadbalancer.

clusterctl generate cluster capi-quickstart --flavor without-lb --kubernetes-version v1.23.3 --control-plane-machine-count=1 --worker-machine-count=1 > capi-quickstart.yaml
 k apply -f capi-quickstart.yaml 

clouds.yaml file
clouds:
  openstack:
    auth:
      auth_url: XXXXXXXXX
      username: "dreynold"
      project_id: 0863a66504634c9b93e916462d434e57
      project_name: "OTT.PC1-2.JENKINS.1"
      user_domain_name: "Default"
      password: XXXXXXXXX
    region_name: "regionOne"
    interface: "public"
    identity_api_version: 3
    verify: false

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I0505 12:11:18.523081       1 openstackcluster_controller.go:300] controller/openstackcluster "msg"="Reconciling Bastion" "cluster"="capi-quickstart" "name"="capi-quickstart" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackCluster" 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x14e6a88]

goroutine 440 [running]:
sigs.k8s.io/cluster-api-provider-openstack/controllers.bastionToInstanceSpec(0xc0002ec000, {0xc0007d0600, 0xc0002ec000})
        /workspace/controllers/openstackcluster_controller.go:365 +0xc8
sigs.k8s.io/cluster-api-provider-openstack/controllers.deleteBastion(0x1a8d720, 0xc00083c000, 0xc0002ec000)
        /workspace/controllers/openstackcluster_controller.go:226 +0x18b
sigs.k8s.io/cluster-api-provider-openstack/controllers.reconcileBastion(0xc00040b900, 0xc00083c000, 0xc0002ec000)
        /workspace/controllers/openstackcluster_controller.go:303 +0x64e
sigs.k8s.io/cluster-api-provider-openstack/controllers.reconcileNormal({0x1a6fd98, 0xc000555050}, 0xc00040b900, 0xc00007a910, 0xc0007fc9f0, 0xc0002ec000)
        /workspace/controllers/openstackcluster_controller.go:263 +0x14b
sigs.k8s.io/cluster-api-provider-openstack/controllers.(*OpenStackClusterReconciler).Reconcile(0xc00062c3c0, {0x1a6fd98, 0xc000555050}, {{{0xc0007fc9f0, 0x1769dc0}, {0xc0007fc9e0, 0x30}}})
        /workspace/controllers/openstackcluster_controller.go:128 +0x69d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc0000d8000, {0x1a6fd98, 0xc000555020}, {{{0xc0007fc9f0, 0x1769dc0}, {0xc0007fc9e0, 0x413c34}}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114 +0x26f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0000d8000, {0x1a6fcf0, 0xc0006a7b00}, {0x16a7c00, 0xc000642200})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311 +0x33e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0000d8000, {0x1a6fcf0, 0xc0006a7b00})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:223 +0x357

**Environment:**
clusterctl version
clusterctl version: &version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.3", GitCommit:"31146bd17a220ef6214c4c7a21f1aa57380b6b1f", GitTreeState:"clean", BuildDate:"2022-03-08T18:52:05Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}

minikube version: v1.25.2
commit: 362d5fdc0a3dbee389b3d3f1034e8023e72bd3a7

kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

NAME="CentOS Linux"
VERSION="7 (Core)"

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

**Comment by danrca** [comment]
Ok, yes my bad. It should be over there. I'll close it out.
