### ISSUE TITLE
Fails to create many nodes (4+ with Kindnet and 9+ with Calico as CNI)

### ISSUE THREAD

**Issue by RobinDeBock** [kubernetes-sigs/cluster-api#6678]
I'll leave this issue for new users who might stumble upon this problem in search result. You can read this message of go straight to [https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files](https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files) to fix it.

This is going to be a long read. I'll keep updating this initial message with new information to keep this issue clear to new readers.
I recommend to read the whole post, as small but important remarks are made / details are discovered throughout.

**What steps did you take and what happened:**
- Created a bootstap cluster with Kind
- Created a workload cluster with 1 control plane node and 1 worker node
- Completed bootstrap & pivot (workload cluster is now management cluster)
- Deleted bootstrap Kind cluster
- Rescaled the machinedeployment to 10 replicas (I want 10 nodes)
- Only 3 nodes are provisioned, 7 stay unavailable even after a lot of time. Phase stays on `ScalingUp`
- (Sometimes the number rises to 5 after a very very long time (multiple hours & standby of host machine))

**What did you expect to happen:**
I expected the number of nodes to reach the desired amount.

**Anything else you would like to add:**
I'll now describe all the steps I took, error messages I got and other information. Because this is a lot, I divided it into sections.
I'll start with the different 'technologies' involved and why they probably are/arent't the source of the problem.

## Docker
Without going into too much depth why I blamed Docker (can't create anymore Kind clusters after my initial cluster gets into that state, an error message in CAPD pointed to Docker). 

The questions I wanted answered:
- Are the nodes provisioned?
  - Yes they are, they all appear in `docker container ls`. 
- Are resource limitations messing with the creation of new nodes?
  - I followed the steps from the CAPI Troubleshooting Guide regarding issues with Docker. As I just reinstalled Docker and completely removed all containers, images, etc from my system... pruning containers etc. did nothing. My system should be as fresh as it can be.
  - I looked this up and apparently Docker containers can use **all of the system resources**. My system isn't close to maxing out memory or CPU usage.
  - Also the maximum number of Docker running containers is far from being reached. 
- Is it version related? As I went to the newest version of Docker Engine after removing Docker Desktop.
  - I went back to the version I did my previous experiment on. I can't confirm that it worked back then as I didn't have the need to create so many nodes.  

## Kind
I know Kind is related to the inner working of CAPD.
So here are some more questions I asked myself:

- Is it version related? 
  - I tried with a different Kind to deploy the initial Cluster but this didn't change anything (to be expected).
- Can I deploy a Kind cluster with the same number (10) of worker nodes?
  - Actually created 11 and this worked fine
- In addition to the previous question, could it have to do something with every node having access to the Docker Socket?
  - Created a new cluster and gave every node the `ExtraMounts` to the Docker socket. This also worked fine.
- Can I create a new Kind cluster while the first cluster is having troubles?
  - This doesn't work with the following configuration and outputs (the output differed between executions of the command):

    <details>
      <summary>kind-test-cluster.yaml (Click to expand)</summary>
    
    ```yaml
    kind: Cluster
    apiVersion: kind.x-k8s.io/v1alpha4
    name: test-cluster
    nodes:
    - role: control-plane
      extraMounts:
        - hostPath: /var/run/docker.sock
          containerPath: /var/run/docker.sock
    ```
    </details>

    <details>
      <summary>kind create cluster (Click to expand)</summary>
    
    ```bash
    robin:$ kind create cluster --image kindest/node:v1.22.7 --config kind-management-cluster.yaml
    Creating cluster "test-cluster" ...
     ✓ Ensuring node image (kindest/node:v1.22.7) 🖼
     ✓ Preparing nodes 📦  
     ✓ Writing configuration 📜 
     ✗ Starting control-plane 🕹️ 
    ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged test-cluster-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1
    Command Output: Error response from daemon: Container 929a2b3501a6f03a4c6af9fa19dd39456ffccc35a2f88dde13d9d3943e2fc8de is not running
    ```
    </details>

    <details>
      <summary>kind create cluster (second output) (Click to expand)</summary>
    
    ```bash
    robin:$ kind create cluster --image kindest/node:v1.22.7 --config kind-management-cluster.yaml
    Creating cluster "test-cluster" ...
     ✓ Ensuring node image (kindest/node:v1.22.7) 🖼
     ✓ Preparing nodes 📦  
     ✗ Writing configuration 📜 
    ERROR: failed to create cluster: failed to generate kubeadm config content: failed to get kubernetes version from node: failed to get file: command "docker exec --privileged test-cluster-control-plane cat /kind/version" failed with error: exit status 126
    Command Output: OCI runtime exec failed: exec failed: cannot exec in a stopped container: unknown
    ```
    </details>

## CNI
If it was network related, changing the CNI should have affect, right?

- Does switching from Kindnet to Calico show any difference?
  - Yes! Now 9 worker nodes are provisioned instead of only 3. However, the same issues (more on this later) arised for this cluster and the last node never provisioned. I think Calico is better equipped to handle problems, but eventually also has to give in. 
- Are network related systems all running?
  - Both when using Kindnet and Calico, many of the network related Pods aren't running. Calico seemed to have the same amount of running Pods than when using Kindnet (this is what I meant with it 'can handle it better').
  - Overview of network related Pods and the node they're running on. All nodes with malfunctioning Pods are also unavailable. This output is from using Kindnet as CNI.
    <details>
      <summary>All  Pods (Click to expand)</summary>
    
    ```bash
    robin:$ kubectl --kubeconfig=master-cluster.kubeconfig get pods -o wide -A
    NAMESPACE                           NAME                                                            READY   STATUS             RESTARTS        AGE   IP            NODE                                   NOMINATED NODE   READINESS GATES
    capd-system                         capd-controller-manager-5d9489dccb-62khd                        1/1     Running            0               22m   192.168.1.5   master-cluster-md-0-556d7fb756-skttj   <none>           <none>
    capi-kubeadm-bootstrap-system       capi-kubeadm-bootstrap-controller-manager-647446bd74-nb4t5      1/1     Running            0               22m   192.168.1.7   master-cluster-md-0-556d7fb756-skttj   <none>           <none>
    capi-kubeadm-control-plane-system   capi-kubeadm-control-plane-controller-manager-cb8bf9c5d-6cfj2   1/1     Running            0               22m   192.168.1.8   master-cluster-md-0-556d7fb756-skttj   <none>           <none>
    capi-system                         capi-controller-manager-cc86586f-skjlb                          1/1     Running            0               22m   192.168.1.6   master-cluster-md-0-556d7fb756-skttj   <none>           <none>
    cert-manager                        cert-manager-86b4798576-ph9w5                                   1/1     Running            0               23m   192.168.1.4   master-cluster-md-0-556d7fb756-skttj   <none>           <none>
    cert-manager                        cert-manager-cainjector-85656d565c-4gbbl                        1/1     Running            0               23m   192.168.1.3   master-cluster-md-0-556d7fb756-skttj   <none>           <none>
    cert-manager                        cert-manager-webhook-8665f985d6-sfqcd                           1/1     Running            0               23m   192.168.1.2   master-cluster-md-0-556d7fb756-skttj   <none>           <none>
    kube-system                         coredns-78fcd69978-56vsb                                        1/1     Running            0               23m   192.168.0.2   master-cluster-control-plane-rgfwm     <none>           <none>
    kube-system                         coredns-78fcd69978-85rxv                                        1/1     Running            0               23m   192.168.0.3   master-cluster-control-plane-rgfwm     <none>           <none>
    kube-system                         etcd-master-cluster-control-plane-rgfwm                         1/1     Running            0               23m   172.19.0.4    master-cluster-control-plane-rgfwm     <none>           <none>
    kube-system                         kindnet-4nxvb                                                   1/1     Running            7 (6m7s ago)    19m   172.19.0.12   master-cluster-md-0-556d7fb756-m7jxv   <none>           <none>
    kube-system                         kindnet-6mn5f                                                   1/1     Running            4 (14m ago)     19m   172.19.0.11   master-cluster-md-0-556d7fb756-ptld2   <none>           <none>
    kube-system                         kindnet-h4kc6                                                   0/1     Error              7 (6m15s ago)   19m   172.19.0.6    master-cluster-md-0-556d7fb756-dpss9   <none>           <none>
    kube-system                         kindnet-hgv87                                                   1/1     Running            7 (5m49s ago)   19m   172.19.0.7    master-cluster-md-0-556d7fb756-rbl7k   <none>           <none>
    kube-system                         kindnet-hndph                                                   1/1     Running            0               23m   172.19.0.5    master-cluster-md-0-556d7fb756-skttj   <none>           <none>
    kube-system                         kindnet-k6wpm                                                   1/1     Running            7 (5m46s ago)   19m   172.19.0.13   master-cluster-md-0-556d7fb756-8sbtd   <none>           <none>
    kube-system                         kindnet-ncswn                                                   1/1     Running            0               19m   172.19.0.9    master-cluster-md-0-556d7fb756-5nmnw   <none>           <none>
    kube-system                         kindnet-pts9n                                                   1/1     Running            0               19m   172.19.0.2    master-cluster-md-0-556d7fb756-pxkc8   <none>           <none>
    kube-system                         kindnet-tctr8                                                   1/1     Running            7 (5m57s ago)   19m   172.19.0.10   master-cluster-md-0-556d7fb756-lr4hw   <none>           <none>
    kube-system                         kindnet-tfbtm                                                   1/1     Running            0               23m   172.19.0.4    master-cluster-control-plane-rgfwm     <none>           <none>
    kube-system                         kube-apiserver-master-cluster-control-plane-rgfwm               1/1     Running            0               23m   172.19.0.4    master-cluster-control-plane-rgfwm     <none>           <none>
    kube-system                         kube-controller-manager-master-cluster-control-plane-rgfwm      1/1     Running            0               23m   172.19.0.4    master-cluster-control-plane-rgfwm     <none>           <none>
    kube-system                         kube-proxy-j962r                                                0/1     CrashLoopBackOff   8 (3m17s ago)   19m   172.19.0.6    master-cluster-md-0-556d7fb756-dpss9   <none>           <none>
    kube-system                         kube-proxy-jwm2d                                                1/1     Running            0               23m   172.19.0.5    master-cluster-md-0-556d7fb756-skttj   <none>           <none>
    kube-system                         kube-proxy-njrcd                                                1/1     Running            0               19m   172.19.0.2    master-cluster-md-0-556d7fb756-pxkc8   <none>           <none>
    kube-system                         kube-proxy-p9fss                                                0/1     CrashLoopBackOff   8 (3m6s ago)    19m   172.19.0.7    master-cluster-md-0-556d7fb756-rbl7k   <none>           <none>
    kube-system                         kube-proxy-pq8jr                                                1/1     Running            0               23m   172.19.0.4    master-cluster-control-plane-rgfwm     <none>           <none>
    kube-system                         kube-proxy-pqvmd                                                0/1     CrashLoopBackOff   8 (2m59s ago)   19m   172.19.0.13   master-cluster-md-0-556d7fb756-8sbtd   <none>           <none>
    kube-system                         kube-proxy-vkssk                                                1/1     Running            0               19m   172.19.0.9    master-cluster-md-0-556d7fb756-5nmnw   <none>           <none>
    kube-system                         kube-proxy-x6hvs                                                1/1     Running            6 (16m ago)     19m   172.19.0.11   master-cluster-md-0-556d7fb756-ptld2   <none>           <none>
    kube-system                         kube-proxy-xhcb5                                                0/1     CrashLoopBackOff   8 (2m57s ago)   19m   172.19.0.12   master-cluster-md-0-556d7fb756-m7jxv   <none>           <none>
    kube-system                         kube-proxy-zwcwk                                                0/1     CrashLoopBackOff   8 (3m10s ago)   19m   172.19.0.10   master-cluster-md-0-556d7fb756-lr4hw   <none>           <none>
    kube-system                         kube-scheduler-master-cluster-control-plane-rgfwm               1/1     Running            0               23m   172.19.0.4    master-cluster-control-plane-rgfwm     <none>           <none>
    ```
    </details>
    
    <details>
      <summary>All running Docker containers (Click to expand)</summary>
    
    ```bash
    robin$ docker container ls
    CONTAINER ID   IMAGE                                COMMAND                  CREATED          STATUS          PORTS                                  NAMES
    438210f41d63   kindest/node:v1.22.7                 "/usr/local/bin/entr…"   39 minutes ago   Up 38 minutes                                          master-cluster-md-0-556d7fb756-ptld2
    2a01edf980da   kindest/node:v1.22.7                 "/usr/local/bin/entr…"   39 minutes ago   Up 38 minutes                                          master-cluster-md-0-556d7fb756-zrbsg
    e6142d4dcc73   kindest/node:v1.22.7                 "/usr/local/bin/entr…"   39 minutes ago   Up 38 minutes                                          master-cluster-md-0-556d7fb756-rbl7k
    e635e028f241   kindest/node:v1.22.7                 "/usr/local/bin/entr…"   39 minutes ago   Up 38 minutes                                          master-cluster-md-0-556d7fb756-5nmnw
    fd10a8b83ac9   kindest/node:v1.22.7                 "/usr/local/bin/entr…"   39 minutes ago   Up 38 minutes                                          master-cluster-md-0-556d7fb756-8sbtd
    257a6b8b228b   kindest/node:v1.22.7                 "/usr/local/bin/entr…"   39 minutes ago   Up 38 minutes                                          master-cluster-md-0-556d7fb756-lr4hw
    7c3e0bb1ce3e   kindest/node:v1.22.7                 "/usr/local/bin/entr…"   39 minutes ago   Up 38 minutes                                          master-cluster-md-0-556d7fb756-m7jxv
    27e06bbc1c68   kindest/node:v1.22.7                 "/usr/local/bin/entr…"   39 minutes ago   Up 39 minutes                                          master-cluster-md-0-556d7fb756-pxkc8
    b6c8ed41e63e   kindest/node:v1.22.7                 "/usr/local/bin/entr…"   39 minutes ago   Up 39 minutes                                          master-cluster-md-0-556d7fb756-dpss9
    0f0fb87686e2   kindest/node:v1.22.7                 "/usr/local/bin/entr…"   42 minutes ago   Up 42 minutes                                          master-cluster-md-0-556d7fb756-skttj
    b868a3c733ca   kindest/node:v1.22.7                 "/usr/local/bin/entr…"   43 minutes ago   Up 43 minutes   43607/tcp, 127.0.0.1:43607->6443/tcp   master-cluster-control-plane-rgfwm
    3bfb0ab03a6b   kindest/haproxy:v20210715-a6da3463   "haproxy -sf 7 -W -d…"   43 minutes ago   Up 43 minutes   40877/tcp, 0.0.0.0:40877->6443/tcp     master-cluster-lb
    ```
    </details>
  - It's easier to check when focussing on one node though:
    <details>
    <summary>All Pods a non-working node (Click to expand)</summary>
    
    ```bash
    robin:$ kubectl --kubeconfig=master-cluster.kubeconfig get pods -o wide -A | grep master-cluster-md-0-556d7fb756-rbl7k
    kube-system                         kindnet-hgv87                                                   0/1     CrashLoopBackOff   19 (4m39s ago)   98m    172.19.0.7    master-cluster-md-0-556d7fb756-rbl7k   <none>           <none>
    kube-system                         kube-proxy-p9fss                                                0/1     Error              24 (5m13s ago)   98m    172.19.0.7    master-cluster-md-0-556d7fb756-rbl7k   <none>           <none>
    ```
    <details>
- Any other noteworthy details about these Pods?
  - The kindnet Pod sometimes comes back online but then immediately crashes.
  - Logs of both Pods from the example:
    <details>
    <summary>kindnet pod logs (Click to expand)</summary>
    
    ```bash
    robin:$ kubectl --kubeconfig=master-cluster.kubeconfig logs -n kube-system pods/kindnet-hgv87
    I0620 14:30:31.098414       1 main.go:80] hostIP = 172.19.0.7
    podIP = 172.19.0.7
    ERROR: Get "https://10.128.0.1:443/api/v1/namespaces/kube-system/configmaps/kubeadm-config": dial tcp 10.128.0.1:443: i/o timeout
    ERROR: Get "https://10.128.0.1:443/api/v1/namespaces/kube-system/configmaps/kube-proxy": dial tcp 10.128.0.1:443: i/o timeout
    panic: Cluster CIDR is not defined
    
    goroutine 1 [running]:
    main.main()
	    /src/cmd/kindnetd/main.go:107 +0xb65
    ```
    </details>
    
    <details>
    <summary>kube-proxy pod logs (Click to expand)</summary>
    
    ```bash
    robin$ kubectl --kubeconfig=master-cluster.kubeconfig logs -n kube-system pods/kube-proxy-p9fss
    F0620 14:35:06.547427       1 server.go:486] failed complete: too many open files
    goroutine 1 [running]:
    k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc00013c001, 0xc00001a000, 0x52, 0xa4)
	    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
    k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x2d82840, 0xc000000003, 0x0, 0x0, 0xc00016e070, 0x0, 0x2531c93, 0x9, 0x1e6, 0x0)
	    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:975 +0x1e5
    k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printf(0x2d82840, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1d80e65, 0x13, 0xc0002956a0, 0x1, ...)
	    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:753 +0x19a
    k8s.io/kubernetes/vendor/k8s.io/klog/v2.Fatalf(...)
	    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1514
    k8s.io/kubernetes/cmd/kube-proxy/app.NewProxyCommand.func1(0xc000741400, 0xc000474820, 0x0, 0x2)
	    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-proxy/app/server.go:486 +0x135
    k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc000741400, 0xc000120160, 0x2, 0x2, 0xc000741400, 0xc000120160)
	    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:856 +0x2c2
    k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000741400, 0xc00013e120, 0x2d82400, 0x0)
	    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:960 +0x375
    k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:897
    main.main()
	    _output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-proxy/proxy.go:48 +0x109
    
    goroutine 18 [chan receive]:
    k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x2d82840)
	    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1169 +0x8b
    created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
	    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:420 +0xdf
    
    goroutine 10 [select]:
    k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x1e40f48, 0x1fbaa40, 0xc00002c000, 0x1, 0xc000114360)
	    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x118
    k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x1e40f48, 0x12a05f200, 0x0, 0x1, 0xc000114360)
	    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
    k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
	    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
    k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Forever(0x1e40f48, 0x12a05f200)
	    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:81 +0x4f
    created by k8s.io/kubernetes/vendor/k8s.io/component-base/logs.InitLogs
	    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/logs/logs.go:58 +0x8a
    ```
    </details>
 
## Solution
The last network-related error gives away what was wrong.
The fix is explained on the [Kind website](https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files). 

**Environment:**

- Cluster-api version: `GitVersion:"v1.1.4"`
- Minikube/KIND version: `v0.12.0 go1.17.8 linux/amd64`
- Kubernetes version: (use `kubectl version`):
  - Client: `GitVersion:"v1.22.3" `
  - Server, both Kind cluster and workload cluster have version `v1.22.7`
- OS (e.g. from `/etc/os-release`): `Ubuntu 20.04.4 LTS`
- Docker
 - Client: `20.10.13`
 - Server: `20.10.13`

/kind bug
/area networking

**Comment by RobinDeBock** [comment]
> Is this the same issue? https://cluster-api.sigs.k8s.io/user/troubleshooting.html#cluster-api-with-docker-desktop---too-many-open-files

It's related. I'm running Docker on Linux, so using Docker Engine, not Docker Desktop.
I'll make a PR where I update this information. Thanks for the link!

**Comment by killianmuldoon** [comment]
I'd be interested in improving our discoverability for the issue too. For me a google search of `"too many open files" cluster api` doesn't actually return our troubleshooting page. 

I think it's more likely to pick up github issues etc. though. I wonder if there's a way we can improve the experience of people who encounter issues like this.

**Comment by RobinDeBock** [comment]
> I'd be interested in improving our discoverability for the issue too. For me a google search of `"too many open files" cluster api` doesn't actually return our troubleshooting page.
> 
> I think it's more likely to pick up github issues etc. though. I wonder if there's a way we can improve the experience of people who encounter issues like this.

Hey @killianmuldoon thanks for mentioning this. It kinda bothered me I overlooked that information and couldn't really figure out why (you start doubting your sanity after searching for an issue for almost half a week).

This could be an agenda item or worth a brainstorm @fabriziopandini @sbueringer
